### ISSUE TITLE
Increase resolution of the image conversion 

### ISSUE THREAD

**Issue by shadowlance** [HEPData/hepdata_lib#100]
The resolution of the current 'pdf -> png image convert' is too bad. 
The density of the Root pdf image output is set to 300 by default. But the defalut density of the ImageMagick output is 72, which will lead to a big resolution lose in the convert output.
My opinoin is to consider adding a option '-density 300' when doing the convert in https://github.com/HEPData/hepdata_lib/blob/0e18ed2446db80701a7ba9fca160a9f146990fb4/hepdata_lib/__init__.py#L288
to get rid of it. Though I don't know if there is a better solution(such as read the image resolution, density before the convert) due to my poor coding skill...

**Comment by AndreasAlbert** [comment]
Hi @shadowlance, thanks for reporting.

In all examples I have seen so far, the resolution of the resulting PNG was fine (see e.g. [here](https://www.hepdata.net/record/ins1700173), but that may be a result of system-dependent default settings?

In any case: Could you provide an example PDF and the resulting PNG output you get to demonstrate?

Thanks

**Comment by shadowlance** [comment]
Hi @AndreasAlbert ,
Thanks for the quick reply! The issue is happening when converting pdf/eps to png(Don't know also happen on other format but I think it will...). Is the example provided is using png or pdf as input? Or it may really due to system-dependent default settings... 
Here is files before the convert and after the convert on my side using the hepdata_lib(.pdf is before and .png is after)
[AccSR_h_High_bin2.pdf](https://github.com/HEPData/hepdata_lib/files/3477258/AccSR_h_High_bin2.pdf)
![AccSR_h_High_bin2](https://user-images.githubusercontent.com/24354408/62627234-99805e00-b95b-11e9-9316-15a556b88277.png)
![thumb_AccSR_h_High_bin2](https://user-images.githubusercontent.com/24354408/62627239-9b4a2180-b95b-11e9-92e9-ab305822dbb5.png)

I also tried to using `convert` command directly at our local server and lxplus server 
`convert -flatten -fuzz 1% -trim +repage AccSR_h_High_bin2.pdf AccSR_h_High_bin2.png`. 
They gave the same result
Thanks

**Comment by shadowlance** [comment]
And this is the png file with '-density 300' added, it seems it doesn't loose resolution(Or lost but could not recongnize by eyes?). 
![AccSR_h_High_bin2](https://user-images.githubusercontent.com/24354408/62628784-8de26680-b95e-11e9-85a0-9aef0afd56c4.png)

**Comment by AndreasAlbert** [comment]
@shadowlance Sorry this took a while. #101  should solve it.

**Comment by shadowlance** [comment]
Thank you so much @AndreasAlbert ! Looking forward this PR is done

**Comment by clelange** [comment]
[v0.2.8](https://github.com/HEPData/hepdata_lib/releases/tag/v0.2.8) contains this improvement and is also available from [PyPI](https://pypi.org/project/hepdata-lib/0.2.8/). You can get it by running `python -m pip install --upgrade hepdata_lib`.

**Comment by shadowlance** [comment]
It works! Thanks a lot!
