### ISSUE TITLE
Move development status to Beta

### ISSUE THREAD

**Issue by clelange** [HEPData/hepdata_lib#106]
We're still in Alpha development status on PyPI. There are still a few features that are useful to have, but I'd propose we move to Beta now with what will be version 0.3.

@AndreasAlbert What do you think?

**Comment by AndreasAlbert** [comment]
Sure, but why stop there?

**Comment by clelange** [comment]
I guess we would need to test individual python versions, e.g. also 3.4, 3.5 to make sure that they are fine and things are stable. Also, work a bit more on the test code quality (e.g. linting) and test the examples consistently as well to have something bullet proof.

**Comment by AndreasAlbert** [comment]
Ok, fair enough. Let's start with beta then.
