### ISSUE TITLE
ROOT file content meaning

### ISSUE THREAD

**Issue by kqf** [HEPData/hepdata_lib#115]
Currently, the content of the ROOT file looks like:
```
 KEY: TH1F	Hist1D_y1;1	doi:10.17182/hepdata.79044.v1/t1
 KEY: TH1F	Hist1D_y1_e1;1	doi:10.17182/hepdata.79044.v1/t1
 KEY: TH1F	Hist1D_y1_e2;1	doi:10.17182/hepdata.79044.v1/t1
 KEY: TGraphAsymmErrors	Graph1D_y1;1	doi:10.17182/hepdata.79044.v1/t1
```
What is the meaning of `Hist1D_y1` histogram? I expected it to contain sum of stat. and syst. errors. However it's not the case. I see that (pseudocode):

```python
errors("Hist1D_y1") != errors("Graph1D_y1")
# but at the same time
(errors("Hist1D_y1_e1") ** 2 + errors("Hist1D_y1_e2") ** 2) ** 0.5 == errors("Graph1D_y1")
```
Not sure if it's the right place, to ask, but I wasn't able to find an answer to my question.

**Comment by AndreasAlbert** [comment]
You are referring to the "export as ROOT" option on the hepdata website, right? In this case, this is really not the right place to ask, and I unfortunately don't know the answer. Paging @GraemeWatt

**Comment by kqf** [comment]
Yes, exactly and sorry for the spam. I thought it's the same mechanism, as the name of the histograms agree. May I ask you tell where or whom should I ask?

**Comment by AndreasAlbert** [comment]
Yeah, my first instinct would really be to ask @GraemeWatt , so let's hope the github ping will alert him to this conversation :D

**Comment by GraemeWatt** [comment]
The `Hist1D_y1` stores the central value, not the errors.  The histograms do not contain a sum in quadrature of the errors, which is only contained in the `Graph1D_y1` object.

The code repository for the ROOT export is https://github.com/HEPData/hepdata-converter.  But unless you want to report a bug or request a feature, it's better to email questions to info@hepdata.net.  I'm going to set up a [Discourse](https://www.discourse.org) forum where users can ask questions like this one in public.
