### ISSUE TITLE
Dump YAML using CSafeDumper (or SafeDumper if not available)

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata_lib#116]
In `hepdata_lib/__init__.py`, replace:
```python
try:
    from yaml import CLoader as Loader, CDumper as Dumper
except ImportError:
    from yaml import Loader, Dumper
```
with:
```python
try:
    from yaml import CSafeLoader as Loader, CSafeDumper as Dumper
except ImportError:
    from yaml import SafeLoader as Loader, SafeDumper as Dumper
```
This will ensure that only standard YAML tags are produced by the `Dumper` and not arbitrary Python objects.  The latter will not be accepted by the [hepdata-validator](https://github.com/HEPData/hepdata-validator).  It's not clear if [hepdata_lib](https://github.com/HEPData/hepdata_lib) uses the `Loader` anywhere, so it could be removed if not.

**Comment by clelange** [comment]
This should be addressed with #137 - please reopen if this is not the case. We now also have a test for that.
