### ISSUE TITLE
Docker container crashes

### ISSUE THREAD

**Issue by GabGallardo** [HEPData/hepdata_lib#132]
I tried to pull the hepdata_lib docker image clelange/hepdata_lib:v0.3.0 (and the same with v0.3.2) on my laptop, but it doesn’t seem to run. It crashes with this error:

```
$ docker run --rm clelange/hepdata_lib:v0.3.2
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python2.7/dist-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 610, in <module>
    from .extensions import (
  File "/usr/local/lib/python2.7/dist-packages/notebook/extensions.py", line 8, in <module>
    from tornado.log import LogFormatter
  File "/usr/local/lib/python2.7/dist-packages/tornado/log.py", line 55
    def _stderr_supports_color() -> bool:
                                 ^
SyntaxError: invalid syntax
```

**Comment by clelange** [comment]
Hi @GabGallardo - thanks for reporting this issue! I can confirm that this is unfortunately happening. For now, and only in case you don't need a jupyter notebook, can you just use the container as follows:

```shell
docker run --rm -it clelange/hepdata_lib:v0.3.2 bash
```

I confirmed that you can then run `python` and also `import hepdata_lib`.

Mind that if you run the container with the `--rm` option and not mounting any directories, your work will be lost. It is probably better to mount your current working directory, e.g.:

```shell
mkdir hepdata_submission
cd hepdata_submission
docker run --rm -it -v $PWD:/home/hepdata clelange/hepdata_lib:v0.3.2 bash
```

In this way, all files that you created in the directory you will end up in when starting the container (which is `/home/hepdata`) will end up in `hepdata_submission` on your local hard disk.

**Comment by GabGallardo** [comment]
Thanks @clelange, this should work for me for now!

**Comment by clelange** [comment]
@GabGallardo can you try again with the ‘latest` tag? If this works for you as well, we can create a new release. Please also see the updated README for instructions to make sure you don't accidentally lose your work.

**Comment by GabGallardo** [comment]
Hi @clelange, 

It launches now, thanks! Just a note on the README. I think you are missing a `:` in `-v ${PWD}:/home/hepdata`?

**Comment by clelange** [comment]
Thanks, good catch! It's fixed now.
