### ISSUE TITLE
readthedocs: Module index not available anymore

### ISSUE THREAD

**Issue by clelange** [HEPData/hepdata_lib#138]
See https://hepdata-lib.readthedocs.io/en/latest/source/hepdata_lib.html

The module index does not build anymore

**Comment by clelange** [comment]
Hi @emanueleusai - thanks for the attempt, but I think it doesn't fix the issue, see https://hepdata-lib--152.org.readthedocs.build/en/152/source/hepdata_lib.html

Could you please check? Did it fix things (what?) for you when building locally?

**Comment by emanueleusai** [comment]
That's unfortunate.
This fix was necessary to make Sphnix run (i.e. "make html") on my setup (LCG_98python3). With that fix I can compile the docs and the index is correctly generated. I assumed that was the reason of the issue on the server side. 

I see now the compilation log and can't see anything that makes the compilation of the index fail:
https://readthedocs.org/projects/hepdata-lib/builds/12778431/
https://readthedocs.org/api/v2/build/12778431.txt

I can try on their environment (i.e. match all their libraries version and commands). Hopefully I can reproduce the issue.
