### ISSUE TITLE
Docker container build broken

### ISSUE THREAD

**Issue by clelange** [HEPData/hepdata_lib#151]
The docker container build is broken, basically for the same reasons the tests got broken: the ROOT `latest` container is now on ubuntu, previously it was CentOS or similar. To fix this, should probably follow changes happening in https://github.com/HEPData/hepdata_lib/pull/150 (i.e. switch to `apt` for software installation).

To fix this:
- [ ] Clone repository.
- [ ] Run `docker build .` and fix issues.
- [ ] Once image has been built, ensure it's working.

**Comment by AndreasAlbert** [comment]
Fixed in #164
