### ISSUE TITLE
 reading_histograms.ipynb crashing SWAN session

### ISSUE THREAD

**Issue by echapon** [HEPData/hepdata_lib#153]
When I am trying to run examples/reading_histograms.ipynb in a Swan session, it crashes at cell 3. More precisely, I get an error message (approximate translation since my Swan is configured in French): "The kernel seems stuck. It is going to restart automatically."

Swan detailed information (I kept all defaults):
- software stack: 99
- Platform: CentOS 7 (gcc8)
- Number of cores: 2
- Memory: 8GB
- Spark cluster: None

**Comment by AndreasAlbert** [comment]
thanks for reporting, I can reproduce your problem. English version of the error message is:
```
The kernel appears to have died. It will restart automatically.
```

**Comment by AndreasAlbert** [comment]
This seems to be a problem with the input ROOT file `mlfit_lm_1000.root`. When I try to open it with the SWAN installation of ROOT, it segfaults. This happens both in interactive ROOT as well as when opening with hepdata_lib. Might be a problem with ROOT version inconsistency?

**Comment by AndreasAlbert** [comment]
This should be resolved now, the file was replaced a while ago. Please reopen if this should pop up again.
