### ISSUE TITLE
Validate submission created by create_files method

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata_lib#160]
After calling the `create_files` method of the `Submission` object, it would be good to validate the files created in the `outdir` directory using the [hepdata-validator](https://github.com/HEPData/hepdata-validator) package.  This could be done in a similar way to the [check.py](https://github.com/HEPData/hepdata-submission/blob/master/scripts/check.py) script, allowing mistakes to be caught offline before uploading to [hepdata.net](https://www.hepdata.net).  For example, the check that uncertainties are not all zero (see #159) would be caught by the validator.  The extra validation step should be switched on by default, perhaps with an option to switch it off.

**Comment by kpedro88** [comment]
At the least, the hepdata-validator package could be installed in the centrally maintained Docker container for easy use.
