### ISSUE TITLE
Add support for one-sided uncertainties

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata_lib#163]
Related to #87 ("Add support for relative uncertainties"), the [Uncertainties](https://hepdata-submission.readthedocs.io/en/latest/data_yaml.html#uncertainties) section of the HEPData submission documentation mentions that a one-sided uncertainty can be represented using an empty string, e.g. `asymerror: {plus: '', minus: -0.3}`, but this is not yet supported by `hepdata_lib`.

**Comment by AndreasAlbert** [comment]
Wouldn't it make more sense to use: ```{plus: 0, minus: -0.3}```?

**Comment by GraemeWatt** [comment]
Yes, I think mostly giving `0` should be fine.  But it was a request from ATLAS a few years ago (see HEPData/hepdata#122) to support one-sided uncertainties as being undefined in one direction rather than strictly zero (see [example table](https://www.hepdata.net/record/ins1468068?version=1&table=Table13)).  I don't think many records have used this feature, but I thought that since HEPData supports it, then so should `hepdata_lib`.  I wouldn't give it a high priority, but it might be worth implementing at the same time as percentage uncertainties (#87).

**Comment by clelange** [comment]
Fixed by #169
