### ISSUE TITLE
Update Release action

### ISSUE THREAD

**Issue by clelange** [HEPData/hepdata_lib#165]
minor

**Comment by AndreasAlbert** [comment]
Could consider automatizing the pypi publication via github actions, see e.g. [here](https://github.com/AndreasAlbert/lhereader/blob/master/.github/workflows/pythonpublish.yml)

in that example, pypi upload is triggered automatically when a new tag is pushed. Just have to figure out how to make sure that it only triggers when the new tag the master (to avoid people randomly tagging stuff)

**Comment by clelange** [comment]
OK, I'll try to look into this next week. I think I found something in this direction somewhere else that protects us from all the pitfalls.

**Comment by GraemeWatt** [comment]
For some other HEPData packages ([hepdata-cli](https://github.com/HEPData/hepdata-cli), [hepdata-converter](https://github.com/HEPData/hepdata-converter), [hepdata-validator](https://github.com/HEPData/hepdata-validator), [hepdata-converter-ws](https://github.com/HEPData/hepdata-converter-ws), [hepdata-converter-ws-client](https://github.com/HEPData/hepdata-converter-ws-client)), we trigger a PyPI upload via GitHub Actions by making a GitHub Release.  This method might work for `hepdata_lib` too.  See, for example, [deploy](https://github.com/HEPData/hepdata-cli/blob/e5462ac96212e534f7c4807d80a28fcb1187efd9/.github/workflows/ci.yml#L40-L58) job for `hepdata-cli`.

**Comment by clelange** [comment]
To fix this eventually, follow https://til.simonwillison.net/pypi/pypi-releases-from-github

**Comment by GraemeWatt** [comment]
I'm already using PyPI's trusted publishing for the other HEPData repositories, so I can take a look if you get stuck.  By the way, could you please add user "hepdata" as a Maintainer or Owner of `hepdata-lib` on PyPI (https://pypi.org/manage/project/hepdata-lib/collaboration/)?

**Comment by clelange** [comment]
> By the way, could you please add user "hepdata" as a Maintainer or Owner of hepdata-lib on PyPI (https://pypi.org/manage/project/hepdata-lib/collaboration/)?

Invite sent.
