### ISSUE TITLE
package 'six' not required on installation

### ISSUE THREAD

**Issue by butsuri43** [HEPData/hepdata_lib#175]
It seems that `six` is not required on installation (https://github.com/HEPData/hepdata_lib/blob/master/setup.py#L11) but it is actually required in helpers.py (https://github.com/HEPData/hepdata_lib/blob/master/hepdata_lib/helpers.py#L11) and caused my fresh installation to run with error.

**Comment by clelange** [comment]
Thanks for pointing this out. One of the dependencies that we have listed had `six` as an dependency, but it is possible that that package moved entirely to Python 3 and removed this dependency. Which Python version are you using and on which operating system?

**Comment by fcatalan92** [comment]
> Thanks for pointing this out. One of the dependencies that we have listed had `six` as an dependency, but it is possible that that package moved entirely to Python 3 and removed this dependency. Which Python version are you using and on which operating system?

Hi, I can confirm this problem with Python 3.8.10 on Ubuntu 20.04.

**Comment by clelange** [comment]
@butsuri43 @fcatalan92 - can you try with v0.8.1 that we just released and if the problem isn't fixed, please reopen this issue?

**Comment by fcatalan92** [comment]
Hi @clelange, v0.8.1 works for me!

**Comment by butsuri43** [comment]
Hey, 

Sorry for being silent.
Indeed v0.8.1 works for me as well on Python 3.9.2.
Many thanks for the fix!
