### ISSUE TITLE
PyYAML warnings on install

### ISSUE THREAD

**Issue by AndreasAlbert** [HEPData/hepdata_lib#18]
This is a PyYAML problem (not our fault). Fixed in https://github.com/yaml/pyyaml/commit/298e07907ae526594069f6fdf31f2f1278cc1ae3

So we just have to wait for PyYAML 3.13 to be released with this fix included

**Comment by AndreasAlbert** [comment]
Workaround in #22 by installing pyyaml from git.
Revisit once PyYAML 3.13 is released.

**Comment by AndreasAlbert** [comment]
The problem is back: https://travis-ci.org/clelange/hepdata_lib/jobs/468928623

**Comment by clelange** [comment]
OK, but since the tests don't fail and installation works, should we consider this to be an issue of our tests/CI?

**Comment by clelange** [comment]
This doesn't seem to be an issue anymore.
