### ISSUE TITLE
Distribution of container on unpacked.cern.ch

### ISSUE THREAD

**Issue by kpedro88** [HEPData/hepdata_lib#186]
Would it be possible to distribute the official Docker container on cvmfs via the CERN unpacked service? It just requires making a PR to update https://gitlab.cern.ch/unpacked/sync/-/blob/master/recipe.yaml, and then the container will get synced automatically. This would make it easier to use with Singularity.

**Comment by clelange** [comment]
Thanks for the suggestion, I've created a merge request: https://gitlab.cern.ch/unpacked/sync/-/merge_requests/101

**Comment by clelange** [comment]
After some synchronisation hickups, the image is now available:

`/cvmfs/unpacked.cern.ch/ghcr.io/hepdata/hepdata_lib:latest`

**Comment by kpedro88** [comment]
Can you add this to the part of the readme that covers Singularity?
