### ISSUE TITLE
Add docs for `add_additional_resource` and support `type` argument

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata_lib#197]
An example of using the [`add_additional_resource`](https://github.com/HEPData/hepdata_lib/blob/4a65a176f85e46345d4fbc4e966acac4a25e4005/hepdata_lib/__init__.py#L58) function of the `Submission` or `Table` objects is not given in either the [documentation](https://hepdata-lib.readthedocs.io/en/latest/usage.html#writing-data) or any of the [example notebooks](https://github.com/HEPData/hepdata_lib#further-examples).  This issue came up in a [HEPData Forum post](https://hepdata-forum.cern.ch/t/additional-non-standard-table-addition-to-a-submission/33).  It would be good to document the usage of `add_additional_resource` and apply it in one or more of the example notebooks.

Also, we just added a new feature to highlight HEPData records with attached HistFactory JSON files (search for [`analysis:HistFactory`](https://www.hepdata.net/search/?q=analysis:HistFactory)).  Currently the "HistFactory" type is triggered by looking for certain words ("histfactory", "pyhf", "likelihoods", "workspaces") in the "description" for certain file types.  But we now also allow a `type: HistFactory` field in the `submission.yaml` file to avoid relying on the description (see [submission docs](https://hepdata-submission.readthedocs.io/en/latest/submission_yaml.html)).  So it would be good if `add_additional_resource` could also accept an optional argument `type`, then set `resource["type"] = type`.

**Comment by clelange** [comment]
+1 that would be good to have. Do you think you can pick this up @GraemeWatt ?
