### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by matthewfeickert** [HEPData/hepdata_lib#219]
Please drop support for Python 2. There are still components of `setup.py` and `setup.cfg` (also a lack of `python_requires`) that indicate that Python 2 is expected and supported

https://github.com/HEPData/hepdata_lib/blob/14fdd3e1d8ca9a9f4873ec903193c2970ee4bf26/setup.py#L41

https://github.com/HEPData/hepdata_lib/blob/14fdd3e1d8ca9a9f4873ec903193c2970ee4bf26/setup.cfg#L6

There is no reason for `hepdata_lib` to be used in the same environment that an LHC analysis needs to be run in, so there is no need to support environments that might be stuck in an environment that is Python 2 only.

**Comment by clelange** [comment]
Thanks for this request. I agree that by now it's about time we drop support for Python 2. I've seen lots of people having issues with their setup, but not anymore over the last year. This will also allow modernising the code base.

**Comment by clelange** [comment]
I guess once https://github.com/HEPData/hepdata_lib/pull/220 is in, we can also officially deprecate 2.7. Any suggestions on which Python version we should use for the image we distribute? 3.9?

**Comment by matthewfeickert** [comment]
> I guess once #220 is in, we can also officially deprecate 2.7. 

Great! I'd suggest putting in a `python_requires` though with a lower bound and making a new minor release so as to not break older Pythons in the future.

> Any suggestions on which Python version we should use for the image we distribute? 3.9?

This is a good question. I generally lean to trying to use the lastest version of Python that is known to work with ROOT, so I would aim for Python 3.10 unless there is a known reason to not use it given the applications that people are using the image for.
