### ISSUE TITLE
Current SWAN defaults are incompatible 

### ISSUE THREAD

**Issue by andrzejnovak** [HEPData/hepdata_lib#225]
Current default SWAN stack (`102b`) already contains latest version of `hepdata_lib`, but an outdated version of `hepdata-validator` which is a dependency. It doesn't seem like SWAN allows for `--user` to overwrite the validator to a newer version.

**Comment by GraemeWatt** [comment]
This seems more an issue for [SWAN](https://swan.web.cern.ch/swan/) (e.g. [Community](https://swan-community.web.cern.ch)) than for the `hepdata_lib` maintainers.  There's some [SWAN docs](https://swan.docs.cern.ch/advanced/install_packages/#python) on installing Python packages.  As explained on the [same page](https://swan.docs.cern.ch/advanced/install_packages/#install-packages-in-cernbox), please [open a ticket](https://sft.its.cern.ch/jira/projects/SPI) to request that `hepdata-validator` be upgraded to the latest v0.3.3 in the next LCG release.

**Comment by GraemeWatt** [comment]
It looks like the `hepdata-validator` upgrade was already addressed in a [MR](https://gitlab.cern.ch/sft/lcgcmake/-/merge_requests/1635) on 16th March 2023.  The latest [LCG Release 103](https://lcginfo.cern.ch/release/103/) (from 26th February 2023) still has `hepdata-validator` v0.2.3, but the [LCG Nightlies](https://lcginfo.cern.ch/#nightlies) have `hepdata-validator` v0.3.3.

**Comment by GraemeWatt** [comment]
I just tried out SWAN for the first time.  The latest recommended release [102b](https://lcginfo.cern.ch/release/102b_swan/) of the software stack does not include `hepdata_lib`, neither does [103](https://lcginfo.cern.ch/release/103swan/).  However, `hepdata_lib` is pre-installed with a compatible `hepdata-validator` version if you instead select the "Bleeding Edge" development version of the software stack when configuring the SWAN environment.
