### ISSUE TITLE
Pip(3) version is outdated

### ISSUE THREAD

**Issue by IzaakWN** [HEPData/hepdata_lib#230]
I would like to report an installation issue I ran into with `pip`.

To get `hepdata_lib` to work on my machine (PSI's T3) where my input files are, I had to modify the installation command with `pip` to `pip3`, e.g.
```shell
source $VO_CMS_SW_DIR/cmsset_default.sh
export CMSSW=CMSSW_11_2_5_hepdata
export SCRAM_ARCH=slc7_amd64_gcc900
scram p -n CMSSW_11_2_5_hepdata CMSSW CMSSW_11_2_5 # cmsrel
cd $CMSSW/src/ && cmsenv
pip3 install hepdata_lib --user # old version
```
However, go some errors for empty bins, e.g.
```shell
$ hepdata-validate -a submission.tar.gz
...
	 error - Uncertainties should not all be zero in 'dependent_variables.values[0].errors'
```
because apparently the `hepdata_lib` version via `pip(3)` was relatively old:
```shell
$ pip3 list | grep hepdata
hepdata-lib                        0.4.1
hepdata-validator                  0.3.3
```
To fix this, I had to get the latest one with
```
$ pip3 install --user https://github.com/HEPData/hepdata_lib/archive/master.zip # latest version
$ pip3 list | grep hepdata
hepdata-lib                        0.12.0
hepdata-validator                  0.3.3
```
Is it possible to change the default `hepdata_lib` version installed by pip to prevent this issue for other users?

**Comment by clelange** [comment]
Hi @IzaakWN - thanks for reporting this issue. However, it is not a pip or hepdata_lib issue, but it's related to the CMSSW release you're using and hepdata_lib already being installed there (the old version you see there). Also, pip/pip3 are provided by CMSSW.

I would advise against using CMSSW and I think we need to remove https://hepdata-lib.readthedocs.io/en/latest/setup.html#setup-on-lxplus-with-cmssw. Instead, please try https://hepdata-lib.readthedocs.io/en/latest/setup.html#using-singularity instead and report any issues.
