### ISSUE TITLE
Output with strings instead of floats 

### ISSUE THREAD

**Issue by kleney** [HEPData/hepdata_lib#264]
I want to include some Sankey diagrams (see attached example) from the recent ATLAS HH→multilepton analysis as HEPData, but I’m running into problems preparing this using the tools available, so I’m wondering if someone here can offer some words of wisdom or pointers in the right direction.

I’ve put all of of the code + data in this CERNBox folder (https://cernbox.cern.ch/s/GxT1OreoeD0Uuif) in case it’s helpful to clarify what exactly I’ve done.

I made the original plots with R so the easiest workaround seemed to be to convert the arrays used in my R dataframe into a TH2F using a small root macro ([Alluvial_to_TH2F.C](https://cernbox.cern.ch/s/D2HatRfYSs78HYM)).  This makes some very ugly but functional root plots (see other attachment) and writes the 2D histograms to a root file (HEPDataAlluvials.root).   I then followed the instructions in [examples/reading_histograms.ipynb](https://github.com/HEPData/hepdata_lib/blob/main/examples/reading_histograms.ipynb) to prepare [TH2F_to_HEPData.ipynb](https://cernbox.cern.ch/s/MOZ91jryqS20Edv).

This runs and I get an output (e.g. [alluvial_outputs/figure_4.yaml](https://cernbox.cern.ch/s/f6o6Gao9695hCD8)) but “HH decay mode” and “Analysis channels” have been converted to floats rather than the strings for each category that I need.  How can I get these to be strings (e.g. "HH decay mode" with value = 0.5 should be "4W", "Analysis channel" with value = 4.5 should be "SS2l" etc etc), other than brute force editing of the output file?

![channel_flow_ml](https://github.com/HEPData/hepdata_lib/assets/24957621/a31f8678-88f9-460b-b292-bdb74f4b7b37)
![ml_channels](https://github.com/HEPData/hepdata_lib/assets/24957621/4f075a6d-a1ba-4e15-810a-a4906f53daa1)

**Comment by matthewfeickert** [comment]
@clelange If you have time to look at this this week feel free to tag me in for questions as well in addition to @kleney.

**Comment by GraemeWatt** [comment]
In [TH2F_to_HEPData.ipynb](https://cernbox.cern.ch/s/MOZ91jryqS20Edv) I think you just need to replace `x` with `x_labels` in the line:
```python
hh_decay.values = ml_channels["x"]
```
and similarly replace `y` with `y_labels` in the line:
```
hh_decay.values = ml_channels["y"]
```
I checked this works for me.

**Comment by kleney** [comment]
Perfect!  I can confirm it has solved my problem.

Thanks so much for your help!  
Katharine
