### ISSUE TITLE
"Open in SWAN" link does not open the notebook

### ISSUE THREAD

**Issue by andresti** [HEPData/hepdata_lib#94]
When clicking on the link https://cern.ch/swanserver/cgi-bin/go?projurl=https://github.com/HEPData/hepdata_lib.git in the manual, a page with empty projects list is opened in SWAN and you have to insert the link manually to open the notebook.
Perhaps the SWAN API has changed?

**Comment by clelange** [comment]
Hi @andresti - thanks for reporting this issue! You are right, there is apparently a small change needed in the URL, adding a `/` after `go` so that the URL reads https://cern.ch/swanserver/cgi-bin/go/?projurl=https://github.com/HEPData/hepdata_lib.git
