### ISSUE TITLE
Add flag to disable features requiring ROOT

### ISSUE THREAD

**Issue by clelange** [HEPData/hepdata_lib#99]
There are use cases where the tool is used but no ROOT installation is available. We should add an option that disables all features that use ROOT to make the other features work independently (e.g. reading in a text file). For ROOT TTrees, we could fall back to uproot.

**Comment by alexander-held** [comment]
Hi, I just ran into this as well and was wondering how straightforward or difficult of an issue you might expect this to be in practice? I can't promise that I'll be able to work on this myself in the near future but would keep an eye open to try and find some help for this.
